<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Demo\Model\Bean;

use Demo\Model\Bean\Generated\AbstractAddress;

/**
 * The Address class maps the 'addresses' table in database.
 */
class Address extends AbstractAddress
{
}
