<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Demo\Model\Bean;

use Demo\Model\Bean\Generated\AbstractCompany;

/**
 * The Company class maps the 'companies' table in database.
 */
class Company extends AbstractCompany
{
}
