<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Demo\Model\Bean;

use Demo\Model\Bean\Generated\AbstractUser;

/**
 * The User class maps the 'users' table in database.
 */
class User extends AbstractUser
{
}
