<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
use Interop\Container\ContainerInterface;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'DEBUG' => 
  array (
    'defaultValue' => true,
    'type' => 'bool',
    'comment' => 'Set to true to enable debug/development mode.',
  ),
  'SECRET' => 
  array (
    'defaultValue' => 'wWe9cpn9NnOFyT4pxt7R',
    'type' => 'string',
    'comment' => 'A random string. It should be different for any application deployed.',
  ),
  'DB_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The database host (the IP address or URL of the database server).',
  ),
  'DB_PORT' => 
  array (
    'defaultValue' => '',
    'type' => 'int',
    'comment' => 'The database port (the port of the database server, keep empty to use default port).',
  ),
  'DB_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The name of your database.',
  ),
  'DB_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to access the database.',
  ),
  'DB_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to access the database.',
  ),
));

$moufManager->setAllVariables(array (
  'splashDefaultControllersNamespace' => 'Demo\\Controller\\',
  'splashDefaultViewsDirectory' => 'views/',
));

$moufManager->addComponentInstances(array (
  'Mouf\\Database\\TDBM\\Utils\\MoufDiListener' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\Utils\\MoufDiListener',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'splashCachePool',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'psr.errorLogLogger',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'strict',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      7 => 
      array (
        'value' => 'return ROOT_URL;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setHttp400Handler' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'annotationReader',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\ControllerRegistry' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ControllerRegistry',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher',
          1 => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher',
    'external' => false,
    'weak' => false,
  ),
  'Mouf\\Mvc\\Splash\\SplashMiddleware' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\SplashMiddleware',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => '__anonymous__af2d_2086964292',
          1 => '__anonymous__af2d_19473817',
          2 => '__anonymous__af2d_1670142579',
          3 => '__anonymous__af2d_42358663',
          4 => '__anonymous__af2d_1346769960',
          5 => '__anonymous__af2d_462579050',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'Psr7Middlewares\\Middleware\\Payload' => 
  array (
    'class' => 'Psr7Middlewares\\Middleware\\Payload',
    'external' => false,
    'weak' => false,
  ),
  '__anonymous__9250_1855149017' => 
  array (
    'class' => 'Doctrine\\Common\\EventManager',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__9250_1960304418' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ResetPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__9250_2073891708' => 
  array (
    'class' => 'Doctrine\\DBAL\\Driver\\PDOMySql\\Driver',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
  ),
  '__anonymous__9250_2097567645' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__9250_215004844' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\SkipPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__9250_412894213' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ApplyAllPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__9250_626195675' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\ListPatchesCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__9250_841093515' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\Commands\\RevertPatchCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_1069355967' => 
  array (
    'class' => 'Mouf\\Utils\\Value\\Variable',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_1346769960' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_1670142579' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_19473817' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container->get(\'whoopsMiddleware\');',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => '__anonymous__af2d_636442517',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_2086964292' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_42358663' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container->get(\'Psr7Middlewares\\\\Middleware\\\\Payload\');',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_462579050' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\Router',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__af2d_636442517' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Condition\\ToCondition',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous__af2d_1069355967',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous__ecb6_1997868403' => 
  array (
    'class' => 'Mouf\\Console\\Command\\MoufRewriteCommand',
    'external' => false,
    'anonymous' => true,
    'weak' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'mouf:rewrite',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'addressDao' => 
  array (
    'class' => 'Demo\\Model\\Dao\\AddressDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'annotationReader' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Annotations\\CachedReader',
    'external' => false,
    'code' => '// Using composer autoloader
$loader = require ROOT_PATH . \'vendor/autoload.php\';
\\Doctrine\\Common\\Annotations\\AnnotationRegistry::registerLoader(array($loader, \'loadClass\'));

// Creating a new AnnotationReader
$reader = new \\Doctrine\\Common\\Annotations\\AnnotationReader();
return new \\Doctrine\\Common\\Annotations\\CachedReader($reader, $container->get("defaultDoctrineCache"));',
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.template.bootstrap/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'template',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setTemplateRenderer' => 'bootstrapRenderer',
      'setDefaultRenderer' => 'defaultRenderer',
    ),
  ),
  'companyApiController' => 
  array (
    'class' => 'Demo\\Controller\\Api\\CompanyApiController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'companyService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'companyDao' => 
  array (
    'class' => 'Demo\\Model\\Dao\\CompanyDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'companyService' => 
  array (
    'class' => 'Demo\\Service\\CompanyService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'companyDao',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'hydrator.company',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/js/bootstrap.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/bootstrap/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'component.jquery' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/components/jquery/jquery.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'console' => 
  array (
    'class' => 'Mouf\\Console\\ConsoleApplication',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setHelperSet' => 'helperSet',
      'setCommands' => 
      array (
        0 => 'dbalRunSqlCommand',
        1 => 'dbalImportCommand',
        2 => 'dbalReservedWordsCommand',
        3 => 'generateCommand',
        4 => '__anonymous__9250_626195675',
        5 => '__anonymous__9250_412894213',
        6 => '__anonymous__9250_2097567645',
        7 => '__anonymous__9250_215004844',
        8 => '__anonymous__9250_841093515',
        9 => '__anonymous__9250_1960304418',
        10 => '__anonymous__ecb6_1997868403',
      ),
    ),
  ),
  'controller.api.user' => 
  array (
    'class' => 'Demo\\Controller\\Api\\UserApiController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'userService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'customRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'custom',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'daoFactory' => 
  array (
    'class' => 'Demo\\Model\\Dao\\Generated\\DaoFactory',
    'external' => false,
    'setterBinds' => 
    array (
      'setAddressDao' => 'addressDao',
      'setCompanyDao' => 'companyDao',
      'setUserDao' => 'userDao',
    ),
    'fieldProperties' => 
    array (
    ),
    'setterProperties' => 
    array (
    ),
    'fieldBinds' => 
    array (
    ),
    'weak' => false,
    'comment' => '',
  ),
  'dbalConnection' => 
  array (
    'class' => 'Doctrine\\DBAL\\Connection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return array(
			    "host" => DB_HOST,
			    "user" => DB_USERNAME,
			    "password" => DB_PASSWORD,
			    "port" => DB_PORT,
			    "dbname" => DB_NAME,
			    "charset" => "utf8",
			    "driverOptions" => array(
			        1002 =>"SET NAMES utf8"
			    )
			);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '__anonymous__9250_2073891708',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'doctrineDbalConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => '__anonymous__9250_1855149017',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalConnectionHelper' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Helper\\ConnectionHelper',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'dbalImportCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ImportCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalReservedWordsCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\ReservedWordsCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbalRunSqlCommand' => 
  array (
    'class' => 'Doctrine\\DBAL\\Tools\\Console\\Command\\RunSqlCommand',
    'external' => false,
    'weak' => false,
  ),
  'dbpatch.9250-20170614172154-patch-initialize-model' => 
  array (
    'class' => 'Mouf\\Database\\Patcher\\DatabasePatch',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patchConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => '9250-20170614172154-patch-initialize-model',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'database/up/20170614172154-patch-initialize-model.sql',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'database/down/20170614172154-patch-initialize-model.sql',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'initialize model',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => 'patch.default_type',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultDoctrineCache' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Doctrine\\Common\\Cache\\ArrayCache',
    'external' => false,
    'code' => '// If DEBUG mode is on, let\'s just use an ArrayCache.
if (DEBUG) {
	$driver = new \\Doctrine\\Common\\Cache\\ArrayCache();
} else {
	// If APC is available, let\'s use APC
	if (extension_loaded("apcu")) {
		$driver = new \\Doctrine\\Common\\Cache\\ApcuCache();
	} else if (extension_loaded("apc")) {
		$driver = new \\Doctrine\\Common\\Cache\\ApcCache();
	} else {
		$driver = new \\Doctrine\\Common\\Cache\\PhpFileCache(sys_get_temp_dir().\'/doctrinecache\');
	}
}
$driver->setNamespace(SECRET);
return $driver;
',
  ),
  'defaultRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\AutoChainRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'rootUrlInlineWebLibrary',
        1 => 'messageServiceLibrary',
        2 => 'component.jquery',
        3 => 'component.bootstrap',
      ),
    ),
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultRenderer',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doctrineDbalConfiguration' => 
  array (
    'class' => 'Doctrine\\DBAL\\Configuration',
    'external' => false,
    'weak' => false,
    'setterProperties' => 
    array (
      'setFilterSchemaAssetsExpression' => 
      array (
        'value' => '/^(?!patches$).*/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'doctrineMoufCache' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Doctrine\\Cache\\DoctrineCacheAdapter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'defaultDoctrineCache',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'generateCommand' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\Commands\\GenerateCommand',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'helperSet' => 
  array (
    'class' => 'Mouf\\Console\\HelperSet',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          'db' => 'dbalConnectionHelper',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.address' => 
  array (
    'class' => 'MetaHydrator\\MetaHydrator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'hydrator.address.number',
          1 => 'hydrator.address.street',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.address.number' => 
  array (
    'class' => 'MetaHydrator\\Handler\\SimpleHydratingHandler',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'number',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'parser.string',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.address.street' => 
  array (
    'class' => 'MetaHydrator\\Handler\\SimpleHydratingHandler',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'street',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'parser.string',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
          0 => 'validator.required',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.company' => 
  array (
    'class' => 'MetaHydrator\\MetaHydrator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'hydrator.company.name',
          1 => 'hydrator.company.activity',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.company.activity' => 
  array (
    'class' => 'MetaHydrator\\Handler\\SimpleHydratingHandler',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'activity',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'parser.string',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'hydrator.company.name' => 
  array (
    'class' => 'MetaHydrator\\Handler\\SimpleHydratingHandler',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'name',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'parser.string',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
          0 => 'validator.pattern.name',
          1 => 'validator.unique.company_name',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
    ),
  ),
  'moufTwigExtension' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigExtension',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return $container;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'namingStrategy' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\Utils\\DefaultNamingStrategy',
    'external' => false,
    'weak' => false,
  ),
  'packageRenderer_mouf/html.utils.weblibrarymanager' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.menu' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.menu/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.messageservice' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.messageservice/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'parser.company.readonly' => 
  array (
    'class' => 'Demo\\Parser\\TDBMRetriever',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'companies',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
          'id' => 'id',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'Erreur base de données',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'parser.string' => 
  array (
    'class' => 'MetaHydrator\\Parser\\StringParser',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Valeur invalide',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patch.default_type' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchType',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Patches that should be always applied should have this type. Typically, use this type for DDL changes or reference data insertion.',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patch.testdata_type' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchType',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'test_data',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Use this type to mark patches that contain test data that should only be used in staging environment.',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patchConnection' => 
  array (
    'class' => 'Mouf\\Database\\Patcher\\PatchConnection',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'patches',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'patchService' => 
  array (
    'class' => 'Mouf\\Utils\\Patcher\\PatchService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'patch.default_type',
          1 => 'patch.testdata_type',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'patchConnection',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setPatchs' => 
      array (
        0 => 'dbpatch.9250-20170614172154-patch-initialize-model',
      ),
    ),
  ),
  'psr.errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'warning',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rendererCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\InMemoryCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'chainWith' => 'apcCacheService',
    ),
  ),
  'rootController' => 
  array (
    'class' => 'Demo\\Controller\\RootController',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'bootstrapTemplate',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'block.content',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'twigEnvironment',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootUrlInlineWebLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rootUrlJsFile',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootUrlJsFile' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlFromFile',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.utils.weblibrarymanager/javascript/rootUrl.php',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'splashCachePool' => 
  array (
    'weak' => false,
    'comment' => '',
    'class' => 'Stash\\Pool',
    'external' => false,
    'code' => '$drivers = [
    new Stash\\Driver\\Ephemeral()
];

if (Stash\\Driver\\Apc::isAvailable()) {
    $drivers[] = new Stash\\Driver\\Apc([
        \'namespace\' => SECRET
    ]);
}

$drivers[] = new Stash\\Driver\\FileSystem([
    \'path\' => sys_get_temp_dir().\'/splash-\'.SECRET
]);

$compositeDriver = new Stash\\Driver\\Composite([\'drivers\'=>$drivers]);

return new Stash\\Pool($compositeDriver);',
  ),
  'tdbmConfiguration' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\MoufConfiguration',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Demo\\Model\\Bean',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Demo\\Model\\Dao',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'dbalConnection',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'namingStrategy',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      4 => 
      array (
        'value' => 'defaultDoctrineCache',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      5 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      6 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      7 => 
      array (
        'value' => 
        array (
          0 => 'Mouf\\Database\\TDBM\\Utils\\MoufDiListener',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setDaoFactoryInstanceName' => 
      array (
        'value' => 'daoFactory',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'tdbmService' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\TDBMService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmConfiguration',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigCacheFileSystem' => 
  array (
    'class' => 'Twig_Cache_Filesystem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '// If we are running on a Unix environment, let\'s prepend the cache with the user id of the PHP process.
// This way, we can avoid rights conflicts.
if (function_exists(\'posix_geteuid\')) {
    $posixGetuid = posix_geteuid();
} else {
    $posixGetuid = \'\';
}
return rtrim(sys_get_temp_dir(), \'/\\\\\').\'/mouftwigtemplatemain_\'.$posixGetuid.str_replace(":", "", ROOT_PATH);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'twigDebugExtension' => 
  array (
    'class' => 'Twig_Extension_Debug',
    'external' => false,
    'weak' => false,
  ),
  'twigEnvironment' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironment',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'twigLoaderFileSystem',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'return array(\'debug\' => DEBUG, \'auto_reload\' => true);',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setExtensions' => 
      array (
        0 => 'moufTwigExtension',
        1 => 'twigDebugExtension',
      ),
      'setCache' => 'twigCacheFileSystem',
    ),
  ),
  'twigLoaderFileSystem' => 
  array (
    'class' => 'Twig_Loader_Filesystem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'return ROOT_PATH;',
        'parametertype' => 'primitive',
        'type' => 'php',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userDao' => 
  array (
    'class' => 'Demo\\Model\\Dao\\UserDao',
    'external' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'userService' => 
  array (
    'class' => 'Demo\\Service\\UserService',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'userDao',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.pattern.email' => 
  array (
    'class' => 'Demo\\Validator\\RegexValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '/^[a-zA-z0-9.-]+\\@[a-zA-z0-9.-]+.[a-zA-Z]+$/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Email invalide',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.pattern.name' => 
  array (
    'class' => 'Demo\\Validator\\RegexValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '/^[a-zA-Zàâäéèêëỳÿŷùüûìïîòôö\' -]*$/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Uniquement des lettres, tirets ou apostrophe',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.pattern.phone' => 
  array (
    'class' => 'Demo\\Validator\\RegexValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '/^(0|\\+33( ?\\(0\\))? ?)[1-9]([-. ]?[0-9]{2}){4}$/',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'Numéro de téléphone invalide',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.required' => 
  array (
    'class' => 'MetaHydrator\\Validator\\NotEmptyValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Ce champ est requis',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.unique.company_name' => 
  array (
    'class' => 'Demo\\Validator\\TDBMUniqueValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'companies',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'name',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'Cette compagnie existe déjà',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'validator.unique.users_email' => 
  array (
    'class' => 'Demo\\Validator\\TDBMUniqueValidator',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'tdbmService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'users',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'email',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 'Cet email est déjà utilisé',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'whoopsMiddleware' => 
  array (
    'class' => 'Middlewares\\Whoops',
    'external' => false,
    'weak' => false,
  ),
));


unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	public function getClosures() {
		return [
			'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
					7 => function(ContainerInterface $container) {
						return ROOT_URL;
					},
				],
			],
			'Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
				],
			],
			'__anonymous__af2d_19473817' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container->get('whoopsMiddleware');
					},
				],
			],
			'__anonymous__af2d_42358663' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container->get('Psr7Middlewares\\Middleware\\Payload');
					},
				],
			],
			'annotationReader' => function(ContainerInterface $container) {
				// Using composer autoloader
$loader = require ROOT_PATH . 'vendor/autoload.php';
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

// Creating a new AnnotationReader
$reader = new \Doctrine\Common\Annotations\AnnotationReader();
return new \Doctrine\Common\Annotations\CachedReader($reader, $container->get("defaultDoctrineCache"));
			},
			'dbalConnection' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return array(
			    "host" => DB_HOST,
			    "user" => DB_USERNAME,
			    "password" => DB_PASSWORD,
			    "port" => DB_PORT,
			    "dbname" => DB_NAME,
			    "charset" => "utf8",
			    "driverOptions" => array(
			        1002 =>"SET NAMES utf8"
			    )
			);
					},
				],
			],
			'defaultDoctrineCache' => function(ContainerInterface $container) {
				// If DEBUG mode is on, let's just use an ArrayCache.
if (DEBUG) {
	$driver = new \Doctrine\Common\Cache\ArrayCache();
} else {
	// If APC is available, let's use APC
	if (extension_loaded("apcu")) {
		$driver = new \Doctrine\Common\Cache\ApcuCache();
	} else if (extension_loaded("apc")) {
		$driver = new \Doctrine\Common\Cache\ApcCache();
	} else {
		$driver = new \Doctrine\Common\Cache\PhpFileCache(sys_get_temp_dir().'/doctrinecache');
	}
}
$driver->setNamespace(SECRET);
return $driver;

			},
			'moufTwigExtension' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return $container;
					},
				],
			],
			'splashCachePool' => function(ContainerInterface $container) {
				$drivers = [
    new Stash\Driver\Ephemeral()
];

if (Stash\Driver\Apc::isAvailable()) {
    $drivers[] = new Stash\Driver\Apc([
        'namespace' => SECRET
    ]);
}

$drivers[] = new Stash\Driver\FileSystem([
    'path' => sys_get_temp_dir().'/splash-'.SECRET
]);

$compositeDriver = new Stash\Driver\Composite(['drivers'=>$drivers]);

return new Stash\Pool($compositeDriver);
			},
			'twigCacheFileSystem' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						// If we are running on a Unix environment, let's prepend the cache with the user id of the PHP process.
// This way, we can avoid rights conflicts.
if (function_exists('posix_geteuid')) {
    $posixGetuid = posix_geteuid();
} else {
    $posixGetuid = '';
}
return rtrim(sys_get_temp_dir(), '/\\').'/mouftwigtemplatemain_'.$posixGetuid.str_replace(":", "", ROOT_PATH);
					},
				],
			],
			'twigEnvironment' => [
				'constructor' => [
					1 => function(ContainerInterface $container) {
						return array('debug' => DEBUG, 'auto_reload' => true);
					},
				],
			],
			'twigLoaderFileSystem' => [
				'constructor' => [
					0 => function(ContainerInterface $container) {
						return ROOT_PATH;
					},
				],
			],
		];
	}
	/**
	 * @return Mouf\Database\TDBM\Utils\MoufDiListener
	 */
	 public static function getMoufDatabaseTDBMUtilsMoufDiListener() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Database\\TDBM\\Utils\\MoufDiListener');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getMoufMvcSplashControllersHttpErrorsController() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\ExceptionRouter
	 */
	 public static function getMoufMvcSplashRoutersExceptionRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\NotFoundRouter
	 */
	 public static function getMoufMvcSplashRoutersNotFoundRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\PhpVarsCheckRouter
	 */
	 public static function getMoufMvcSplashRoutersPhpVarsCheckRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\SplashDefaultRouter
	 */
	 public static function getMoufMvcSplashRoutersSplashDefaultRouter() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ControllerAnalyzer
	 */
	 public static function getMoufMvcSplashServicesControllerAnalyzer() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ControllerAnalyzer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ControllerRegistry
	 */
	 public static function getMoufMvcSplashServicesControllerRegistry() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ControllerRegistry');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\MoufControllerExplorer
	 */
	 public static function getMoufMvcSplashServicesMoufControllerExplorer() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\MoufControllerExplorer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\MoufExplorerUrlProvider
	 */
	 public static function getMoufMvcSplashServicesMoufExplorerUrlProvider() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\MoufExplorerUrlProvider');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\ParameterFetcherRegistry
	 */
	 public static function getMoufMvcSplashServicesParameterFetcherRegistry() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\ParameterFetcherRegistry');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\SplashRequestFetcher
	 */
	 public static function getMoufMvcSplashServicesSplashRequestFetcher() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\SplashRequestFetcher');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Services\SplashRequestParameterFetcher
	 */
	 public static function getMoufMvcSplashServicesSplashRequestParameterFetcher() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\Services\\SplashRequestParameterFetcher');
	 }

	/**
	 * @return Mouf\Mvc\Splash\SplashMiddleware
	 */
	 public static function getMoufMvcSplashSplashMiddleware() {
	 	return MoufManager::getMoufManager()->get('Mouf\\Mvc\\Splash\\SplashMiddleware');
	 }

	/**
	 * @return Psr7Middlewares\Middleware\Payload
	 */
	 public static function getPsr7MiddlewaresMiddlewarePayload() {
	 	return MoufManager::getMoufManager()->get('Psr7Middlewares\\Middleware\\Payload');
	 }

	/**
	 * @return Demo\Model\Dao\AddressDao
	 */
	 public static function getAddressDao() {
	 	return MoufManager::getMoufManager()->get('addressDao');
	 }

	/**
	 * @return Doctrine\Common\Annotations\CachedReader
	 */
	 public static function getAnnotationReader() {
	 	return MoufManager::getMoufManager()->get('annotationReader');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->get('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->get('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->get('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->get('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->get('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->get('block.right');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getBootstrapRenderer() {
	 	return MoufManager::getMoufManager()->get('bootstrapRenderer');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->get('bootstrapTemplate');
	 }

	/**
	 * @return Demo\Controller\Api\CompanyApiController
	 */
	 public static function getCompanyApiController() {
	 	return MoufManager::getMoufManager()->get('companyApiController');
	 }

	/**
	 * @return Demo\Model\Dao\CompanyDao
	 */
	 public static function getCompanyDao() {
	 	return MoufManager::getMoufManager()->get('companyDao');
	 }

	/**
	 * @return Demo\Service\CompanyService
	 */
	 public static function getCompanyService() {
	 	return MoufManager::getMoufManager()->get('companyService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_bootstrap() {
	 	return MoufManager::getMoufManager()->get('component.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getComponent_jquery() {
	 	return MoufManager::getMoufManager()->get('component.jquery');
	 }

	/**
	 * @return Mouf\Console\ConsoleApplication
	 */
	 public static function getConsole() {
	 	return MoufManager::getMoufManager()->get('console');
	 }

	/**
	 * @return Demo\Controller\Api\UserApiController
	 */
	 public static function getController_api_user() {
	 	return MoufManager::getMoufManager()->get('controller.api.user');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getCustomRenderer() {
	 	return MoufManager::getMoufManager()->get('customRenderer');
	 }

	/**
	 * @return Demo\Model\Dao\Generated\DaoFactory
	 */
	 public static function getDaoFactory() {
	 	return MoufManager::getMoufManager()->get('daoFactory');
	 }

	/**
	 * @return Doctrine\DBAL\Connection
	 */
	 public static function getDbalConnection() {
	 	return MoufManager::getMoufManager()->get('dbalConnection');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper
	 */
	 public static function getDbalConnectionHelper() {
	 	return MoufManager::getMoufManager()->get('dbalConnectionHelper');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ImportCommand
	 */
	 public static function getDbalImportCommand() {
	 	return MoufManager::getMoufManager()->get('dbalImportCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\ReservedWordsCommand
	 */
	 public static function getDbalReservedWordsCommand() {
	 	return MoufManager::getMoufManager()->get('dbalReservedWordsCommand');
	 }

	/**
	 * @return Doctrine\DBAL\Tools\Console\Command\RunSqlCommand
	 */
	 public static function getDbalRunSqlCommand() {
	 	return MoufManager::getMoufManager()->get('dbalRunSqlCommand');
	 }

	/**
	 * @return Mouf\Database\Patcher\DatabasePatch
	 */
	 public static function getDbpatch_925020170614172154patchinitializemodel() {
	 	return MoufManager::getMoufManager()->get('dbpatch.9250-20170614172154-patch-initialize-model');
	 }

	/**
	 * @return Doctrine\Common\Cache\ArrayCache
	 */
	 public static function getDefaultDoctrineCache() {
	 	return MoufManager::getMoufManager()->get('defaultDoctrineCache');
	 }

	/**
	 * @return Mouf\Html\Renderer\AutoChainRenderer
	 */
	 public static function getDefaultRenderer() {
	 	return MoufManager::getMoufManager()->get('defaultRenderer');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->get('defaultWebLibraryManager');
	 }

	/**
	 * @return Doctrine\DBAL\Configuration
	 */
	 public static function getDoctrineDbalConfiguration() {
	 	return MoufManager::getMoufManager()->get('doctrineDbalConfiguration');
	 }

	/**
	 * @return Mouf\Utils\Common\Doctrine\Cache\DoctrineCacheAdapter
	 */
	 public static function getDoctrineMoufCache() {
	 	return MoufManager::getMoufManager()->get('doctrineMoufCache');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->get('fileCacheService');
	 }

	/**
	 * @return Mouf\Database\TDBM\Commands\GenerateCommand
	 */
	 public static function getGenerateCommand() {
	 	return MoufManager::getMoufManager()->get('generateCommand');
	 }

	/**
	 * @return Mouf\Console\HelperSet
	 */
	 public static function getHelperSet() {
	 	return MoufManager::getMoufManager()->get('helperSet');
	 }

	/**
	 * @return MetaHydrator\MetaHydrator
	 */
	 public static function getHydrator_address() {
	 	return MoufManager::getMoufManager()->get('hydrator.address');
	 }

	/**
	 * @return MetaHydrator\Handler\SimpleHydratingHandler
	 */
	 public static function getHydrator_address_number() {
	 	return MoufManager::getMoufManager()->get('hydrator.address.number');
	 }

	/**
	 * @return MetaHydrator\Handler\SimpleHydratingHandler
	 */
	 public static function getHydrator_address_street() {
	 	return MoufManager::getMoufManager()->get('hydrator.address.street');
	 }

	/**
	 * @return MetaHydrator\MetaHydrator
	 */
	 public static function getHydrator_company() {
	 	return MoufManager::getMoufManager()->get('hydrator.company');
	 }

	/**
	 * @return MetaHydrator\Handler\SimpleHydratingHandler
	 */
	 public static function getHydrator_company_activity() {
	 	return MoufManager::getMoufManager()->get('hydrator.company.activity');
	 }

	/**
	 * @return MetaHydrator\Handler\SimpleHydratingHandler
	 */
	 public static function getHydrator_company_name() {
	 	return MoufManager::getMoufManager()->get('hydrator.company.name');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->get('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->get('messageWidget');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigExtension
	 */
	 public static function getMoufTwigExtension() {
	 	return MoufManager::getMoufManager()->get('moufTwigExtension');
	 }

	/**
	 * @return Mouf\Database\TDBM\Utils\DefaultNamingStrategy
	 */
	 public static function getNamingStrategy() {
	 	return MoufManager::getMoufManager()->get('namingStrategy');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_utils_weblibrarymanager() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.utils.weblibrarymanager');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_menu() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.menu');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_messageservice() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.messageservice');
	 }

	/**
	 * @return Demo\Parser\TDBMRetriever
	 */
	 public static function getParser_company_readonly() {
	 	return MoufManager::getMoufManager()->get('parser.company.readonly');
	 }

	/**
	 * @return MetaHydrator\Parser\StringParser
	 */
	 public static function getParser_string() {
	 	return MoufManager::getMoufManager()->get('parser.string');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchType
	 */
	 public static function getPatch_default_type() {
	 	return MoufManager::getMoufManager()->get('patch.default_type');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchType
	 */
	 public static function getPatch_testdata_type() {
	 	return MoufManager::getMoufManager()->get('patch.testdata_type');
	 }

	/**
	 * @return Mouf\Database\Patcher\PatchConnection
	 */
	 public static function getPatchConnection() {
	 	return MoufManager::getMoufManager()->get('patchConnection');
	 }

	/**
	 * @return Mouf\Utils\Patcher\PatchService
	 */
	 public static function getPatchService() {
	 	return MoufManager::getMoufManager()->get('patchService');
	 }

	/**
	 * @return Mouf\Utils\Log\Psr\ErrorLogLogger
	 */
	 public static function getPsr_errorLogLogger() {
	 	return MoufManager::getMoufManager()->get('psr.errorLogLogger');
	 }

	/**
	 * @return Mouf\Utils\Cache\InMemoryCache
	 */
	 public static function getRendererCacheService() {
	 	return MoufManager::getMoufManager()->get('rendererCacheService');
	 }

	/**
	 * @return Demo\Controller\RootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->get('rootController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\InlineWebLibrary
	 */
	 public static function getRootUrlInlineWebLibrary() {
	 	return MoufManager::getMoufManager()->get('rootUrlInlineWebLibrary');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlFromFile
	 */
	 public static function getRootUrlJsFile() {
	 	return MoufManager::getMoufManager()->get('rootUrlJsFile');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->get('sessionManager');
	 }

	/**
	 * @return Stash\Pool
	 */
	 public static function getSplashCachePool() {
	 	return MoufManager::getMoufManager()->get('splashCachePool');
	 }

	/**
	 * @return Mouf\Database\TDBM\MoufConfiguration
	 */
	 public static function getTdbmConfiguration() {
	 	return MoufManager::getMoufManager()->get('tdbmConfiguration');
	 }

	/**
	 * @return Mouf\Database\TDBM\TDBMService
	 */
	 public static function getTdbmService() {
	 	return MoufManager::getMoufManager()->get('tdbmService');
	 }

	/**
	 * @return Twig_Cache_Filesystem
	 */
	 public static function getTwigCacheFileSystem() {
	 	return MoufManager::getMoufManager()->get('twigCacheFileSystem');
	 }

	/**
	 * @return Twig_Extension_Debug
	 */
	 public static function getTwigDebugExtension() {
	 	return MoufManager::getMoufManager()->get('twigDebugExtension');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigEnvironment
	 */
	 public static function getTwigEnvironment() {
	 	return MoufManager::getMoufManager()->get('twigEnvironment');
	 }

	/**
	 * @return Twig_Loader_Filesystem
	 */
	 public static function getTwigLoaderFileSystem() {
	 	return MoufManager::getMoufManager()->get('twigLoaderFileSystem');
	 }

	/**
	 * @return Demo\Model\Dao\UserDao
	 */
	 public static function getUserDao() {
	 	return MoufManager::getMoufManager()->get('userDao');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->get('userMessageService');
	 }

	/**
	 * @return Demo\Service\UserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->get('userService');
	 }

	/**
	 * @return Demo\Validator\RegexValidator
	 */
	 public static function getValidator_pattern_email() {
	 	return MoufManager::getMoufManager()->get('validator.pattern.email');
	 }

	/**
	 * @return Demo\Validator\RegexValidator
	 */
	 public static function getValidator_pattern_name() {
	 	return MoufManager::getMoufManager()->get('validator.pattern.name');
	 }

	/**
	 * @return Demo\Validator\RegexValidator
	 */
	 public static function getValidator_pattern_phone() {
	 	return MoufManager::getMoufManager()->get('validator.pattern.phone');
	 }

	/**
	 * @return MetaHydrator\Validator\NotEmptyValidator
	 */
	 public static function getValidator_required() {
	 	return MoufManager::getMoufManager()->get('validator.required');
	 }

	/**
	 * @return Demo\Validator\TDBMUniqueValidator
	 */
	 public static function getValidator_unique_company_name() {
	 	return MoufManager::getMoufManager()->get('validator.unique.company_name');
	 }

	/**
	 * @return Demo\Validator\TDBMUniqueValidator
	 */
	 public static function getValidator_unique_users_email() {
	 	return MoufManager::getMoufManager()->get('validator.unique.users_email');
	 }

	/**
	 * @return Middlewares\Whoops
	 */
	 public static function getWhoopsMiddleware() {
	 	return MoufManager::getMoufManager()->get('whoopsMiddleware');
	 }

}
