<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Demo\Model\Dao;

use Demo\Model\Dao\Generated\AbstractAddressDao;

/**
 * The AddressDao class will maintain the persistence of Address class into the addresses table.
 */
class AddressDao extends AbstractAddressDao
{
}
