<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace Demo\Model\Dao;

use Demo\Model\Dao\Generated\AbstractCompanyDao;

/**
 * The CompanyDao class will maintain the persistence of Company class into the companies table.
 */
class CompanyDao extends AbstractCompanyDao
{
}
